
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------


using Terminal.Gui;

namespace Solitare
{

    public partial class StartView
    {
        public StartView()
        {
            InitializeComponent();

            seedTextField.ColorScheme = new Terminal.Gui.ColorScheme(
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.BrightGreen),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green)
            );
            seedTextField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider("")
            {
                Pattern = "^[0-9]+$",
                Text = "123"
            };
            startButton.Accepting += (s, e) =>
            {
                if (!seedTextField.IsValid) return;

                int index = difficultyRadio.SelectedItem;
                Difficulty difficulty = index == 0 ? Difficulty.Easy : Difficulty.Hard;

                var seed = int.Parse(seedTextField.Text);
                var game = new Game(seed, difficulty);
                var view = new GameView(game);
                Application.Run(view);
            };
        }
    }
}
