
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

namespace myproj
{
    using Microsoft.Extensions.Logging;
    using Terminal.Gui;


    enum Difficulty
    {
        Easy,
        Hard
    }


    public partial class MyView
    {

        public MyView()
        {
            InitializeComponent();
            startButton.Accepting += (s, e) =>
            {
                int index = difficultyRadio.SelectedItem;
                Difficulty difficulty = index == 0 ? Difficulty.Easy : Difficulty.Hard;
                MessageBox.Query("Game", "difficulty" + difficulty, "Ok");
            };
        }
    }
}
