
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace myproj {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme whiteOnGray;
        
        private Terminal.Gui.Label difficultyLabel;
        
        private Terminal.Gui.RadioGroup difficultyRadio;
        
        private Terminal.Gui.Button startButton;
        
        private void InitializeComponent() {
            this.startButton = new Terminal.Gui.Button();
            this.difficultyRadio = new Terminal.Gui.RadioGroup();
            this.difficultyLabel = new Terminal.Gui.Label();
            this.greyOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4285953654u, 4278190080u), new Terminal.Gui.Attribute(4278190080u, 4285953654u), new Terminal.Gui.Attribute(4285953654u, 4278190080u), new Terminal.Gui.Attribute(4285953654u, 4278190080u), new Terminal.Gui.Attribute(4278190080u, 4285953654u));
            this.tgDefault = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294967295u, 4278190335u), new Terminal.Gui.Attribute(4278190080u, 4286611584u), new Terminal.Gui.Attribute(4284602070u, 4278190335u), new Terminal.Gui.Attribute(4294967040u, 4278190335u), new Terminal.Gui.Attribute(4282087679u, 4286611584u));
            this.blueOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4282087679u, 4278190080u), new Terminal.Gui.Attribute(4282087679u, 4294570405u), new Terminal.Gui.Attribute(4278255615u, 4278190080u), new Terminal.Gui.Attribute(4286611584u, 4278190080u), new Terminal.Gui.Attribute(4278255615u, 4294570405u));
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294901760u, 4278190080u), new Terminal.Gui.Attribute(4294901760u, 4294967040u), new Terminal.Gui.Attribute(4293347414u, 4278190080u), new Terminal.Gui.Attribute(4286611584u, 4278190080u), new Terminal.Gui.Attribute(4293347414u, 4294967040u));
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4278222848u, 4278190080u), new Terminal.Gui.Attribute(4278222848u, 4294902015u), new Terminal.Gui.Attribute(4279682572u, 4278190080u), new Terminal.Gui.Attribute(4286611584u, 4278190080u), new Terminal.Gui.Attribute(4279682572u, 4294902015u));
            this.whiteOnGray = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294967295u, 4278190080u), new Terminal.Gui.Attribute(4294967295u, 4278190080u), new Terminal.Gui.Attribute(4294967295u, 4278190080u), new Terminal.Gui.Attribute(4294967295u, 4278190080u), new Terminal.Gui.Attribute(4294967295u, 4278190080u));
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.ColorScheme = this.blueOnBlack;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Pasjans gigathon 2025 (Kliknij Esc by wyjść)";
            this.difficultyLabel.Width = Dim.Auto();
            this.difficultyLabel.Height = Dim.Auto();
            this.difficultyLabel.X = Pos.Center();
            this.difficultyLabel.Y = Pos.Center() - 2;
            this.difficultyLabel.Visible = true;
            this.difficultyLabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.difficultyLabel.CanFocus = false;
            this.difficultyLabel.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.difficultyLabel.Data = "difficultyLabel";
            this.difficultyLabel.Text = "Wybierz poziom trudności:";
            this.difficultyLabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.difficultyLabel);
            this.difficultyRadio.Width = 10;
            this.difficultyRadio.Height = 2;
            this.difficultyRadio.X = Pos.Center();
            this.difficultyRadio.Y = Pos.Center();
            this.difficultyRadio.Visible = true;
            this.difficultyRadio.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.difficultyRadio.CanFocus = true;
            this.difficultyRadio.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.difficultyRadio.Data = "difficultyRadio";
            this.difficultyRadio.TextAlignment = Terminal.Gui.Alignment.Start;
            this.difficultyRadio.RadioLabels = new string[] {
                    "Łatwy",
                    "Trudny"};
            this.Add(this.difficultyRadio);
            this.startButton.Width = Dim.Auto();
            this.startButton.Height = Dim.Auto();
            this.startButton.X = Pos.Center();
            this.startButton.Y = Pos.Center() + 3;
            this.startButton.Visible = true;
            this.startButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.startButton.ColorScheme = this.blueOnBlack;
            this.startButton.CanFocus = true;
            this.startButton.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.startButton.Data = "startButton";
            this.startButton.Text = "Rozpocznij gręki";
            this.startButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.startButton.IsDefault = false;
            this.Add(this.startButton);
        }
    }
}
