
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace solitare
{
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    using Color = Terminal.Gui.Color;

    public partial class GameView : Terminal.Gui.Window
    {

        private Terminal.Gui.ColorScheme greenScheme;

        private Terminal.Gui.Label difficultyLabel;

        private Terminal.Gui.RadioGroup difficultyRadio;

        private Terminal.Gui.Button startButton;

        private void InitializeComponent()
        {
            this.startButton = new Terminal.Gui.Button();
            this.difficultyRadio = new Terminal.Gui.RadioGroup();
            this.difficultyLabel = new Terminal.Gui.Label();
            this.greenScheme = new Terminal.Gui.ColorScheme(
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green)
            );
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.ColorScheme = this.greenScheme;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Pasjans gigathon 2025 (Kliknij Esc by wyjść)";
        }
    }
}
