
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui;

namespace myproj
{
    public partial class GameView
    {

        private DeckViewFinal[] finalDeckViews;
        private DeckViewInitial[] initialDeckViews;
        private DeckViewReserve reserveDecView;

        public GameView(GameState gameState)
        {
            InitializeComponent();

            finalDeckViews = gameState.finalDecks.Select((deck, i) =>
            {
                var deckView = new DeckViewFinal(deck, Pos.Absolute(3 + (i * (CardView.width + 1))), Pos.Absolute(3));
                this.Add(deckView);
                return deckView;
            }
            ).ToArray();

            initialDeckViews = gameState.initialDecks.Select((deck, i) =>
            {
                var deckView = new DeckViewInitial(deck, Pos.Absolute(3 + (i * (CardView.width + 1))), Pos.Absolute(15));
                this.Add(deckView);
                return deckView;
            }
            ).ToArray();

            {
                reserveDecView = new DeckViewReserve(gameState.reserveDeck, Pos.Absolute(50), Pos.Absolute(3));
                this.Add(reserveDecView);
            }
        }
    }
}
