
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui;

namespace solitare
{
    public partial class GameView
    {

        private DeckViewFinal[] finalDeckViews;
        private DeckViewInitial[] initialDeckViews;
        private DeckViewReserve reserveDeckView;
        private ReserveView reserveNextButton;

        public static IDeckView selectedDeck = null;
        public static CardView selectedCard = null;

        public GameView(GameState gameState)
        {
            InitializeComponent();

            var initialDeckY = 3;
            initialDeckViews = gameState.initialDecks.Select((deck, i) =>
            {
                var deckView = new DeckViewInitial(deck, Pos.Absolute(3 + (i * (CardView.width + 1))), Pos.Absolute(initialDeckY));
                this.Add(deckView);
                return deckView;
            }
            ).ToArray();

            var finalDeckY = initialDeckY + CardView.height + 14 + 3;
            finalDeckViews = gameState.finalDecks.Select((deck, i) =>
            {
                var deckView = new DeckViewFinal(deck, Pos.Absolute(3 + (i * (CardView.width + 1))), Pos.Absolute(finalDeckY));
                this.Add(deckView);
                return deckView;
            }
            ).ToArray();

            var reserveNextX = 50;
            reserveNextButton = new ReserveView(
                    reserveNextX,
                    finalDeckY,
                    (s, e) => reserveDeckView.NextCard()
            );
            this.Add(reserveNextButton);

            reserveDeckView = new DeckViewReserve(
                    gameState.reserveDeck,
                    Pos.Absolute(reserveNextX + CardView.width + 1),
                    Pos.Absolute(finalDeckY),
                    (isEmpty) => reserveNextButton.SetEmpty(isEmpty));
            this.Add(reserveDeckView);

        }
    }
}
