
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

namespace myproj
{

    public partial class StartView
    {
        public StartView()
        {
            InitializeComponent();
            startButton.Accepting += (s, e) =>
            {
                int index = difficultyRadio.SelectedItem;
                Difficulty difficulty = index == 0 ? Difficulty.Easy : Difficulty.Hard;

                new Game(difficulty);
            };
        }
    }
}
