
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace solitare
{
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    using Color = Terminal.Gui.Color;

    public partial class StartView : Terminal.Gui.Window
    {

        private Terminal.Gui.ColorScheme greenScheme;

        private Terminal.Gui.Label difficultyLabel;

        private Terminal.Gui.RadioGroup difficultyRadio;

        private Terminal.Gui.Label seedLabel;

        private Terminal.Gui.TextValidateField seedTextField;

        private Terminal.Gui.Button startButton;

        private void InitializeComponent()
        {
            this.startButton = new Terminal.Gui.Button();
            this.seedTextField = new Terminal.Gui.TextValidateField();
            this.seedLabel = new Terminal.Gui.Label();
            this.difficultyRadio = new Terminal.Gui.RadioGroup();
            this.difficultyLabel = new Terminal.Gui.Label();
            this.greenScheme = new Terminal.Gui.ColorScheme(
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.BrightGreen),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green),
                new Terminal.Gui.Attribute(Color.Black, Color.Green)
            );
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;

            var baseY = Pos.Center() - 4;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.ColorScheme = this.greenScheme;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Pasjans gigathon 2025 (Kliknij Esc by wyjść)";
            this.difficultyLabel.Width = Dim.Auto();
            this.difficultyLabel.Height = Dim.Auto();
            this.difficultyLabel.X = Pos.Center();
            this.difficultyLabel.Y = baseY;
            this.difficultyLabel.Visible = true;
            this.difficultyLabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.difficultyLabel.CanFocus = false;
            this.difficultyLabel.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.difficultyLabel.Data = "difficultyLabel";
            this.difficultyLabel.Text = "Poziom trudności:";
            this.difficultyLabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.difficultyLabel);
            this.difficultyRadio.Width = 10;
            this.difficultyRadio.Height = 2;
            this.difficultyRadio.X = Pos.Center();
            this.difficultyRadio.Y = baseY + 2;
            this.difficultyRadio.Visible = true;
            this.difficultyRadio.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.difficultyRadio.CanFocus = true;
            this.difficultyRadio.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.difficultyRadio.Data = "difficultyRadio";
            this.difficultyRadio.TextAlignment = Terminal.Gui.Alignment.Start;
            this.difficultyRadio.RadioLabels = new string[] {
                    "Łatwy",
                    "Trudny"};
            this.Add(this.difficultyRadio);
            this.seedLabel.Width = Dim.Auto();
            this.seedLabel.Height = Dim.Auto();
            this.seedLabel.X = Pos.Center();
            this.seedLabel.Y = baseY + 4;
            this.seedLabel.Visible = true;
            this.seedLabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.seedLabel.CanFocus = false;
            this.seedLabel.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.seedLabel.Data = "seedLabel";
            this.seedLabel.Text = "Ziarno gry (seed)";
            this.seedLabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.seedLabel);
            this.seedTextField.Width = 15;
            this.seedTextField.Height = 1;
            this.seedTextField.X = Pos.Center();
            this.seedTextField.Y = baseY + 5;
            this.seedTextField.Visible = true;
            this.seedTextField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.seedTextField.CanFocus = true;
            this.seedTextField.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.seedTextField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider(".*");
            this.seedTextField.Data = "seedTextField";
            this.seedTextField.Text = "123";
            this.seedTextField.TextAlignment = Terminal.Gui.Alignment.Center;
            this.Add(this.seedTextField);
            this.startButton.Width = Dim.Auto();
            this.startButton.Height = Dim.Auto();
            this.startButton.X = Pos.Center();
            this.startButton.Y = baseY + 8;
            this.startButton.Visible = true;
            this.startButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.startButton.ColorScheme = this.greenScheme;
            this.startButton.CanFocus = true;
            this.startButton.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.startButton.Data = "startButton";
            this.startButton.Text = "Rozpocznij grę";
            this.startButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.startButton.IsDefault = false;
            this.Add(this.startButton);
        }
    }
}
